config/routes.rb
Chef::Application.routes.draw do

  resources :food_stocks

  resources :foods

  get "signup", to: "users#signup", :as => "signup"
  get "signin" => "user_sessions#new", :as => "signin"
  get "signout" => "user_sessions#signout", :as => "signout"

  get "pages/index"

  root to:'pages#index'

  resources :users
  resources :user_sessions

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :producer, class_name: "Organization"

  def name_with_brand
    "#{producer.name} - #{name}"
  end
end

app/models/food_stock.rb
class FoodStock < ActiveRecord::Base
  belongs_to :food
  belongs_to :user
end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encryp_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encryp_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :restore_session, :access_control

  def access_control
    redirect_to root_path, :alert => "Please sign in first." unless signed_in?
  end

  def restore_session
    begin
      @current_user = User.find(session[:user_id]) unless !session[:user_id]
    rescue ActiveRecord::RecordNotFound
      reset_session
      redirect_to root_path, :alert => "User not found."
    end
  end

  helper_method :signed_in?
  def signed_in?
    !@current_user.nil?
  end
end

app/controllers/food_stocks_controller.rb
class FoodStocksController < ApplicationController
  before_action :set_food_stock, only: [:show, :edit, :update, :destroy]

  # GET /food_stocks
  # GET /food_stocks.json
  def index
    @food_stocks = FoodStock.all
  end

  # GET /food_stocks/1
  # GET /food_stocks/1.json
  def show
  end

  # GET /food_stocks/new
  def new
    @food_stock = FoodStock.new
  end

  # GET /food_stocks/1/edit
  def edit
  end

  # POST /food_stocks
  # POST /food_stocks.json
  def create
    @food_stock = FoodStock.new(food_stock_params)

    respond_to do |format|
      if @food_stock.save
        format.html { redirect_to '/food_stocks', notice: 'Food stock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food_stock }
      else
        format.html { render action: 'new' }
        format.json { render json: @food_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_stocks/1
  # PATCH/PUT /food_stocks/1.json
  def update
    respond_to do |format|
      if @food_stock.update(food_stock_params)
        format.html { redirect_to @food_stock, notice: 'Food stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_stocks/1
  # DELETE /food_stocks/1.json
  def destroy
    @food_stock.destroy
    respond_to do |format|
      format.html { redirect_to food_stocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_stock
      @food_stock = FoodStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_stock_params
      params.require(:food_stock).permit(:food_id, :user_id, :quantity)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :producer_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :access_control, only: [:index]

  def index
    @user_session = UserSession.new
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :access_control, only: [:create]

  def create
    email = params.require(:email)
    password = params.require(:password)

    user = User.authenticate(email, password)

    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => 'Welcome in Chef! Thank you for signing in!'
    else
      redirect_to root_path, :alert => "Incorrect email or password. Please try again."
    end
  end

  def signout
    reset_session
    redirect_to root_path, :notice => "You have been signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :access_control, only: [:create, :signup]

  def create
    @user = User.new(params.require(:user).permit!)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "signup"
    end
  end

  def signup
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/food_stocks_helper.rb
module FoodStocksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_stocks/_form.html.erb
<%= form_for(@food_stock) do |f| %>
  <% if @food_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_stock.errors.count, "error") %> prohibited this food_stock from being saved:</h2>

      <ul>
      <% @food_stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food, for: "food[food_id]" %><br>
    <%= collection_select :food, :food_id, Food.all, :id, :name_with_brand, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_stocks/edit.html.erb
<h1>Editing food_stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_stock %> |
<%= link_to 'Back', food_stocks_path %>

app/views/food_stocks/index.html.erb
<h1>Listing food_stocks</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>User</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @food_stocks.each do |food_stock| %>
      <tr>
        <td><%= food_stock.food %></td>
        <td><%= food_stock.user %></td>
        <td><%= food_stock.quantity %></td>
        <td><%= link_to 'Show', food_stock %></td>
        <td><%= link_to 'Edit', edit_food_stock_path(food_stock) %></td>
        <td><%= link_to 'Destroy', food_stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add food', new_food_stock_path %>

app/views/food_stocks/new.html.erb
<h1>New food_stock</h1>

<%= render 'form' %>

<%= link_to 'Back', food_stocks_path %>

app/views/food_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @food_stock.food %>
</p>

<p>
  <strong>User:</strong>
  <%= @food_stock.user %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @food_stock.quantity %>
</p>

<%= link_to 'Edit', edit_food_stock_path(@food_stock) %> |
<%= link_to 'Back', food_stocks_path %>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :producer_id %><br>
    <%= f.text_field :producer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Producer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.producer %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @food.producer %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chef</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !flash.empty? %>
  <div class="flash">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class => name %>
  <% end %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Chef</h1>
<% if notice %>
  <div class="notice">
    <%= notice %>
  </div>
<% end %>
<% if !signed_in? %>
  <%= link_to "Sign up", '/signup', {class: "signup"} %>
  <%= form_tag('/user_sessions', class: "login") do %>
    <%= label_tag :email, 'Email' %>
    <%= email_field_tag :email %>

    <%= label_tag :password, 'Password' %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign in" %>
  <% end %>
<% end %>

app/views/user_sessions/login.html.erb
<h1>UserSessions#login</h1>
<p>Find me in app/views/user_sessions/login.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/signup.html.erb
<div class="signup-page">
  <h1>Sign up</h1>
  <%= form_for @user, html: {class: "signup"} do |f| %>
    <% if @user.errors.any? %>
      <div class="errors">
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up" %>
  <% end %>
</div>